using Finance.Net.Models.Yahoo;
using Finance.Net.Models.Yahoo.Dtos;
using Finance.Net.Utilities;

namespace Finance.Net.Mappings;

internal static class YahooQuoteMapper
{
    public static Quote ToQuote(this QuoteResponse src) => new()
    {
        Language = src.Language,
        Region = src.Region,
        QuoteType = src.QuoteType,
        TypeDisp = src.TypeDisp,
        QuoteSourceName = src.QuoteSourceName,
        CustomPriceAlertConfidence = src.CustomPriceAlertConfidence,
        Currency = src.Currency,
        Exchange = src.Exchange,
        ShortName = src.ShortName,
        LongName = src.LongName,
        ExchangeTimezoneName = src.ExchangeTimezoneName,
        ExchangeTimezoneShortName = src.ExchangeTimezoneShortName,
        GmtOffSetMilliseconds = src.GmtOffSetMilliseconds,
        Market = src.Market,
        EsgPopulated = src.EsgPopulated,
        RegularMarketChangePercent = src.RegularMarketChangePercent,
        RegularMarketPrice = src.RegularMarketPrice,
        MarketState = src.MarketState,
        FullExchangeName = src.FullExchangeName,
        FinancialCurrency = src.FinancialCurrency,
        RegularMarketOpen = src.RegularMarketOpen,
        AverageDailyVolume3Month = src.AverageDailyVolume3Month,
        AverageDailyVolume10Day = src.AverageDailyVolume10Day,
        FiftyTwoWeekLowChange = src.FiftyTwoWeekLowChange,
        FiftyTwoWeekLowChangePercent = src.FiftyTwoWeekLowChangePercent,
        FiftyTwoWeekRange = src.FiftyTwoWeekRange,
        FiftyTwoWeekHighChange = src.FiftyTwoWeekHighChange,
        FiftyTwoWeekHighChangePercent = src.FiftyTwoWeekHighChangePercent,
        FiftyTwoWeekLow = src.FiftyTwoWeekLow,
        FiftyTwoWeekHigh = src.FiftyTwoWeekHigh,
        FiftyTwoWeekChangePercent = src.FiftyTwoWeekChangePercent,
        EarningsDate = Helper.UnixToDateTime(src.EarningsTimestamp),
        EarningsDateStart = Helper.UnixToDateTime(src.EarningsTimestampStart),
        EarningsDateEnd = Helper.UnixToDateTime(src.EarningsTimestampEnd),
        EarningsCallDateStart = Helper.UnixToDateTime(src.EarningsCallTimestampStart),
        EarningsCallDateEnd = Helper.UnixToDateTime(src.EarningsCallTimestampEnd),
        IsEarningsDateEstimate = src.IsEarningsDateEstimate,
        TrailingAnnualDividendRate = src.TrailingAnnualDividendRate,
        TrailingPe = src.TrailingPe,
        DividendRate = src.DividendRate,
        DividendDate = Helper.UnixToDateTime(src.DividendDate),
        TrailingAnnualDividendYield = src.TrailingAnnualDividendYield,
        DividendYield = src.DividendYield,
        EpsTrailingTwelveMonths = src.EpsTrailingTwelveMonths,
        EpsForward = src.EpsForward,
        EpsCurrentYear = src.EpsCurrentYear,
        PriceEpsCurrentYear = src.PriceEpsCurrentYear,
        SharesOutstanding = src.SharesOutstanding,
        BookValue = src.BookValue,
        FiftyDayAverage = src.FiftyDayAverage,
        FiftyDayAverageChange = src.FiftyDayAverageChange,
        PriceHint = src.PriceHint,
        PostMarketChangePercent = src.PostMarketChangePercent,
        PostMarketTime = Helper.UnixToDateTime(src.PostMarketTime),
        PostMarketPrice = src.PostMarketPrice,
        PostMarketChange = src.PostMarketChange,
        RegularMarketChange = src.RegularMarketChange,
        RegularMarketTime = Helper.UnixToDateTime(src.RegularMarketTime),
        RegularMarketDayHigh = src.RegularMarketDayHigh,
        RegularMarketDayRange = src.RegularMarketDayRange,
        RegularMarketDayLow = src.RegularMarketDayLow,
        RegularMarketVolume = src.RegularMarketVolume,
        RegularMarketPreviousClose = src.RegularMarketPreviousClose,
        Bid = src.Bid,
        Ask = src.Ask,
        BidSize = src.BidSize,
        AskSize = src.AskSize,
        FiftyDayAverageChangePercent = src.FiftyDayAverageChangePercent,
        TwoHundredDayAverage = src.TwoHundredDayAverage,
        TwoHundredDayAverageChange = src.TwoHundredDayAverageChange,
        TwoHundredDayAverageChangePercent = src.TwoHundredDayAverageChangePercent,
        MarketCap = src.MarketCap,
        ForwardPe = src.ForwardPe,
        PriceToBook = src.PriceToBook,
        SourceInterval = src.SourceInterval,
        ExchangeDataDelayedBy = src.ExchangeDataDelayedBy,
        AverageAnalystRating = src.AverageAnalystRating,
        Tradeable = src.Tradeable,
        CryptoTradeable = src.CryptoTradeable,
        HasPrePostMarketData = src.HasPrePostMarketData,
        FirstTradeDate = Helper.UnixMillisecsToDate(src.FirstTradeDateMilliseconds),
        DisplayName = src.DisplayName,
        Symbol = src.Symbol,
    };
}
