namespace Finance.Net.Models.Yahoo;

/// <summary>
/// Represents a financial report with various financial metrics related to revenue, expenses, income, and other key financial performance indicators.
/// </summary>
public record FinancialReport
{
    /// <summary>
    /// The total revenue generated by the company.
    /// </summary>
    public decimal? TotalRevenue { get; set; }

    /// <summary>
    /// The cost of revenue, representing the direct costs attributable to the production of goods or services sold.
    /// </summary>
    public decimal? CostOfRevenue { get; set; }

    /// <summary>
    /// The gross profit, calculated as Total Revenue minus Cost of Revenue.
    /// </summary>
    public decimal? GrossProfit { get; set; }

    /// <summary>
    /// The operating expenses incurred by the company in the course of its business activities.
    /// </summary>
    public decimal? OperatingExpense { get; set; }

    /// <summary>
    /// The operating income, calculated as Gross Profit minus Operating Expenses.
    /// </summary>
    public decimal? OperatingIncome { get; set; }

    /// <summary>
    /// The net non-operating interest income or expense, representing income or expense from interest outside core business operations.
    /// </summary>
    public decimal? NetNonOperatingInterestIncomeExpense { get; set; }

    /// <summary>
    /// Other income or expenses not directly related to the company's core operations.
    /// </summary>
    public decimal? OtherIncomeExpense { get; set; }

    /// <summary>
    /// The pretax income before accounting for tax provision.
    /// </summary>
    public decimal? PretaxIncome { get; set; }

    /// <summary>
    /// The provision for income taxes based on pretax income.
    /// </summary>
    public decimal? TaxProvision { get; set; }

    /// <summary>
    /// The net income attributable to common stockholders after tax provisions.
    /// </summary>
    public decimal? NetIncomeCommonStockholders { get; set; }

    /// <summary>
    /// The diluted net income available to common stockholders, accounting for potential dilution from convertible securities.
    /// </summary>
    public decimal? DilutedNIAvailableToComStockholders { get; set; }

    /// <summary>
    /// The basic earnings per share (EPS), calculated as Net Income divided by basic average shares outstanding.
    /// </summary>
    public decimal? BasicEPS { get; set; }

    /// <summary>
    /// The diluted earnings per share (EPS), accounting for potential dilution from convertible securities.
    /// </summary>
    public decimal? DilutedEPS { get; set; }

    /// <summary>
    /// The basic average number of shares outstanding for the EPS calculation.
    /// </summary>
    public decimal? BasicAverageShares { get; set; }

    /// <summary>
    /// The diluted average number of shares outstanding for the EPS calculation, considering potential dilution.
    /// </summary>
    public decimal? DilutedAverageShares { get; set; }

    /// <summary>
    /// The total operating income as reported in the financial statements.
    /// </summary>
    public decimal? TotalOperatingIncomeAsReported { get; set; }

    /// <summary>
    /// The total expenses incurred by the company during the period.
    /// </summary>
    public decimal? TotalExpenses { get; set; }

    /// <summary>
    /// The net income from continuing and discontinued operations, including any minority interest adjustments.
    /// </summary>
    public decimal? NetIncomeFromContinuingAndDiscontinuedOperation { get; set; }

    /// <summary>
    /// The normalized income, adjusted for one-time items or unusual events.
    /// </summary>
    public decimal? NormalizedIncome { get; set; }

    /// <summary>
    /// The income derived from interest-bearing assets.
    /// </summary>
    public decimal? InterestIncome { get; set; }

    /// <summary>
    /// The expenses incurred from interest-bearing liabilities.
    /// </summary>
    public decimal? InterestExpense { get; set; }

    /// <summary>
    /// The net interest income, calculated as Interest Income minus Interest Expense.
    /// </summary>
    public decimal? NetInterestIncome { get; set; }

    /// <summary>
    /// Earnings Before Interest and Taxes (EBIT), a measure of a company's profitability that excludes interest and tax expenses.
    /// </summary>
    public decimal? EBIT { get; set; }

    /// <summary>
    /// Earnings Before Interest, Taxes, Depreciation, and Amortization (EBITDA), a measure of operating performance.
    /// </summary>
    public decimal? EBITDA { get; set; }

    /// <summary>
    /// The reconciled cost of revenue, adjusted for accounting conventions or one-time items.
    /// </summary>
    public decimal? ReconciledCostOfRevenue { get; set; }

    /// <summary>
    /// The reconciled depreciation expense, adjusted for non-recurring items.
    /// </summary>
    public decimal? ReconciledDepreciation { get; set; }

    /// <summary>
    /// The net income from continuing operations, adjusted for minority interest.
    /// </summary>
    public decimal? NetIncomeFromContinuingOperationNetMinorityInterest { get; set; }

    /// <summary>
    /// The total value of unusual items, excluding goodwill adjustments.
    /// </summary>
    public decimal? TotalUnusualItemsExcludingGoodwill { get; set; }

    /// <summary>
    /// The total value of unusual items, including goodwill.
    /// </summary>
    public decimal? TotalUnusualItems { get; set; }

    /// <summary>
    /// The normalized EBITDA, adjusted for one-time or unusual items.
    /// </summary>
    public decimal? NormalizedEBITDA { get; set; }

    /// <summary>
    /// The tax rate used for financial calculations.
    /// </summary>
    public decimal? TaxRateForCalcs { get; set; }

    /// <summary>
    /// The tax effect of unusual items, representing the tax impact of non-recurring items.
    /// </summary>
    public decimal? TaxEffectOfUnusualItems { get; set; }
}
